# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6b3c52ebf260df3b27516afcb2e974fc6c14c83924d6f1e53c894433ae7e5ec6827cf5b5bb25bcd1998f187702007eac99e42fcd6b7f74267aa11679f237870

test:
  secret_key_base: ae20ef57419703f4582c7a012cdd5cef3df7be0aee8d3eac2ec9d7884fc4b8ad143d4852f876ce509ea55b639cc3b6aa0d0aea70f4d6ae5e4f79c51689fc8cfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
